// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.DAL;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(HospitalDB))]
    [Migration("20251107002453_RemoveObsoleteColumns")]
    partial class RemoveObsoleteColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Appointment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AppointmentDefinitionsAppointmentDefinitionID")
                        .HasColumnType("int");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<bool>("MemberArrived")
                        .HasColumnType("bit");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("TimeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AppointmentDefinitionsAppointmentDefinitionID");

                    b.HasIndex("MemberID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("WebApp.Models.AppointmentDefinition", b =>
                {
                    b.Property<int>("AppointmentDefinitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentDefinitionID"));

                    b.Property<int>("DateEntityId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<int>("PolyclinicID")
                        .HasColumnType("int");

                    b.Property<int>("TimeID")
                        .HasColumnType("int");

                    b.HasKey("AppointmentDefinitionID");

                    b.HasIndex("DateEntityId");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PolyclinicID");

                    b.HasIndex("TimeID");

                    b.ToTable("AppointmentDefinitions");
                });

            modelBuilder.Entity("WebApp.Models.DateEntity", b =>
                {
                    b.Property<int>("DateEntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DateEntityID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("TimeId")
                        .HasColumnType("int");

                    b.HasKey("DateEntityID");

                    b.HasIndex("DoctorId");

                    b.HasIndex("TimeId");

                    b.ToTable("Dates");

                    b.HasData(
                        new
                        {
                            DateEntityID = 1,
                            Date = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            TimeId = 1
                        },
                        new
                        {
                            DateEntityID = 2,
                            Date = new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            TimeId = 1
                        },
                        new
                        {
                            DateEntityID = 3,
                            Date = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            TimeId = 2
                        },
                        new
                        {
                            DateEntityID = 4,
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            TimeId = 2
                        },
                        new
                        {
                            DateEntityID = 5,
                            Date = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            TimeId = 3
                        },
                        new
                        {
                            DateEntityID = 6,
                            Date = new DateTime(2025, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            TimeId = 3
                        },
                        new
                        {
                            DateEntityID = 7,
                            Date = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            TimeId = 4
                        },
                        new
                        {
                            DateEntityID = 8,
                            Date = new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            TimeId = 4
                        },
                        new
                        {
                            DateEntityID = 9,
                            Date = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            TimeId = 5
                        },
                        new
                        {
                            DateEntityID = 10,
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            TimeId = 5
                        },
                        new
                        {
                            DateEntityID = 11,
                            Date = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            TimeId = 6
                        },
                        new
                        {
                            DateEntityID = 12,
                            Date = new DateTime(2025, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            TimeId = 6
                        },
                        new
                        {
                            DateEntityID = 13,
                            Date = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            TimeId = 7
                        },
                        new
                        {
                            DateEntityID = 14,
                            Date = new DateTime(2025, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            TimeId = 7
                        },
                        new
                        {
                            DateEntityID = 15,
                            Date = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            TimeId = 1
                        },
                        new
                        {
                            DateEntityID = 16,
                            Date = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            TimeId = 1
                        },
                        new
                        {
                            DateEntityID = 17,
                            Date = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            TimeId = 2
                        },
                        new
                        {
                            DateEntityID = 18,
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            TimeId = 2
                        },
                        new
                        {
                            DateEntityID = 19,
                            Date = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            TimeId = 1
                        },
                        new
                        {
                            DateEntityID = 20,
                            Date = new DateTime(2025, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            TimeId = 1
                        },
                        new
                        {
                            DateEntityID = 21,
                            Date = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            TimeId = 3
                        },
                        new
                        {
                            DateEntityID = 22,
                            Date = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            TimeId = 3
                        },
                        new
                        {
                            DateEntityID = 23,
                            Date = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            TimeId = 5
                        },
                        new
                        {
                            DateEntityID = 24,
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            TimeId = 5
                        },
                        new
                        {
                            DateEntityID = 25,
                            Date = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            TimeId = 2
                        },
                        new
                        {
                            DateEntityID = 26,
                            Date = new DateTime(2025, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            TimeId = 2
                        },
                        new
                        {
                            DateEntityID = 27,
                            Date = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            TimeId = 4
                        },
                        new
                        {
                            DateEntityID = 28,
                            Date = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            TimeId = 4
                        },
                        new
                        {
                            DateEntityID = 29,
                            Date = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            TimeId = 7
                        },
                        new
                        {
                            DateEntityID = 30,
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            TimeId = 7
                        },
                        new
                        {
                            DateEntityID = 31,
                            Date = new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 6,
                            TimeId = 3
                        },
                        new
                        {
                            DateEntityID = 32,
                            Date = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 6,
                            TimeId = 3
                        },
                        new
                        {
                            DateEntityID = 33,
                            Date = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 6,
                            TimeId = 4
                        },
                        new
                        {
                            DateEntityID = 34,
                            Date = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 6,
                            TimeId = 4
                        },
                        new
                        {
                            DateEntityID = 35,
                            Date = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 6,
                            TimeId = 6
                        },
                        new
                        {
                            DateEntityID = 36,
                            Date = new DateTime(2025, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 6,
                            TimeId = 6
                        },
                        new
                        {
                            DateEntityID = 37,
                            Date = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 7,
                            TimeId = 3
                        },
                        new
                        {
                            DateEntityID = 38,
                            Date = new DateTime(2025, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 7,
                            TimeId = 3
                        },
                        new
                        {
                            DateEntityID = 39,
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 7,
                            TimeId = 5
                        },
                        new
                        {
                            DateEntityID = 40,
                            Date = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 7,
                            TimeId = 5
                        },
                        new
                        {
                            DateEntityID = 41,
                            Date = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 7,
                            TimeId = 6
                        },
                        new
                        {
                            DateEntityID = 42,
                            Date = new DateTime(2025, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 7,
                            TimeId = 6
                        });
                });

            modelBuilder.Entity("WebApp.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorID"));

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolyclinicID")
                        .HasColumnType("int");

                    b.HasKey("DoctorID");

                    b.HasIndex("PolyclinicID");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorID = 1,
                            DoctorName = "Petar Petrovski",
                            PolyclinicID = 1
                        },
                        new
                        {
                            DoctorID = 2,
                            DoctorName = "Ivana Ivanovska",
                            PolyclinicID = 1
                        },
                        new
                        {
                            DoctorID = 3,
                            DoctorName = "Dimitar Dimitrovski",
                            PolyclinicID = 2
                        },
                        new
                        {
                            DoctorID = 4,
                            DoctorName = "Elena Nikolovska",
                            PolyclinicID = 2
                        },
                        new
                        {
                            DoctorID = 5,
                            DoctorName = "Milena Stojanovska",
                            PolyclinicID = 3
                        },
                        new
                        {
                            DoctorID = 6,
                            DoctorName = "Stefan Stefanovski",
                            PolyclinicID = 3
                        },
                        new
                        {
                            DoctorID = 7,
                            DoctorName = "Aleksandar Petkovski",
                            PolyclinicID = 3
                        });
                });

            modelBuilder.Entity("WebApp.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Polyclinic", b =>
                {
                    b.Property<int>("PolyclinicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolyclinicID"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolyclinicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolyclinicID");

                    b.ToTable("Polyclinics");

                    b.HasData(
                        new
                        {
                            PolyclinicID = 1,
                            Image = "Image1.jpg",
                            PolyclinicName = "Kulak Burun Boğaz"
                        },
                        new
                        {
                            PolyclinicID = 2,
                            Image = "Image2.jpg",
                            PolyclinicName = "Genel Cerrahi"
                        },
                        new
                        {
                            PolyclinicID = 3,
                            Image = "Image3.jpg",
                            PolyclinicName = "Göz"
                        });
                });

            modelBuilder.Entity("WebApp.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Member",
                            NormalizedName = "Member"
                        });
                });

            modelBuilder.Entity("WebApp.Models.Time", b =>
                {
                    b.Property<int>("TimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeID"));

                    b.Property<string>("AppointmentTimes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TimeID");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            TimeID = 1,
                            AppointmentTimes = "10"
                        },
                        new
                        {
                            TimeID = 2,
                            AppointmentTimes = "11"
                        },
                        new
                        {
                            TimeID = 3,
                            AppointmentTimes = "12"
                        },
                        new
                        {
                            TimeID = 4,
                            AppointmentTimes = "13"
                        },
                        new
                        {
                            TimeID = 5,
                            AppointmentTimes = "14"
                        },
                        new
                        {
                            TimeID = 6,
                            AppointmentTimes = "15"
                        },
                        new
                        {
                            TimeID = 7,
                            AppointmentTimes = "16"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Appointment_VM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Appointment_VMs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("WebApp.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("WebApp.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("WebApp.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("WebApp.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("WebApp.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Models.Appointment", b =>
                {
                    b.HasOne("WebApp.Models.AppointmentDefinition", "AppointmentDefinitions")
                        .WithMany()
                        .HasForeignKey("AppointmentDefinitionsAppointmentDefinitionID");

                    b.HasOne("WebApp.Models.Member", "Member")
                        .WithMany("Appointments")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppointmentDefinitions");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("WebApp.Models.AppointmentDefinition", b =>
                {
                    b.HasOne("WebApp.Models.DateEntity", "Date")
                        .WithMany("AppointmentDefinitions")
                        .HasForeignKey("DateEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Doctor", "Doctor")
                        .WithMany("AppointmentDefinitions")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Polyclinic", "Polyclinic")
                        .WithMany("AppointmentDefinitions")
                        .HasForeignKey("PolyclinicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Time", "Time")
                        .WithMany("AppointmentDefinitions")
                        .HasForeignKey("TimeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Date");

                    b.Navigation("Doctor");

                    b.Navigation("Polyclinic");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("WebApp.Models.DateEntity", b =>
                {
                    b.HasOne("WebApp.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("WebApp.Models.Doctor", b =>
                {
                    b.HasOne("WebApp.Models.Polyclinic", "Polyclinic")
                        .WithMany()
                        .HasForeignKey("PolyclinicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Polyclinic");
                });

            modelBuilder.Entity("WebApp.Models.DateEntity", b =>
                {
                    b.Navigation("AppointmentDefinitions");
                });

            modelBuilder.Entity("WebApp.Models.Doctor", b =>
                {
                    b.Navigation("AppointmentDefinitions");
                });

            modelBuilder.Entity("WebApp.Models.Member", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("WebApp.Models.Polyclinic", b =>
                {
                    b.Navigation("AppointmentDefinitions");
                });

            modelBuilder.Entity("WebApp.Models.Time", b =>
                {
                    b.Navigation("AppointmentDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
